GET http://localhost:3005/api/blogs

###

PUT http://localhost:3005/api/blogs/6068f9775eea4f0b7b41acc4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpqampvbmF0aGFuIiwiaWQiOiI2MDZiYmIwMjZkNjhlZTQ1ZGRmMzFjOWYiLCJpYXQiOjE2MTc3NTk5ODh9.5QzQjqtnpGumssoxIzQWQUIA8qLsKA5Mi8CfFIvPk_Q

{
    "title": "How to be baller",
    "author": "Jonny the dog",
    "url": "http://google.com",
    "likes": 11
  }

###

POST http://localhost:3005/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MDc5MDM3OWQ2Y2Y2Mjk0MThlYjk5YmEiLCJpYXQiOjE2MTg1NDM1MzV9.nzsYqEtgAFYFiDjGeEzKJhsfiFPHYzy3J4yrTlnnTOQ

{
    "title": "How to be a dog",
    "author": "Jonny the dog",
    "url": "http://example.com",
    "likes": 118
  }

###

DELETE http://localhost:3005/api/blogs/6077d394a0c6616f2042190f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpqampvbmF0aGFuIiwiaWQiOiI2MDZiYmIwMjZkNjhlZTQ1ZGRmMzFjOWYiLCJpYXQiOjE2MTc3NTk5ODh9.5QzQjqtnpGumssoxIzQWQUIA8qLsKA5Mi8CfFIvPk_Q
